### PR TITLE
Declare header files for PlatformIO

### PR DESCRIPTION
**Pull request by ivankravets**
Hi,

Please accept this PR that adds header files according to https://docs.platformio.org/en/latest/librarymanager/config.html#headers

Developers will see them soon in the new version of PlatformIO Package Registry.

Thanks in advance!

### CODE REVIEW

**Comment by pvint** [comment]
Hey, thanks Ivan!

I don't personally use PlatformIO often, and just one question:
Is the "examples" section not used? (I see that you removed it, and I will defer to your expertise, but I wanted to be certain it wasn't in error)

**Comment by ivankravets** [comment]
> Is the "examples" section not used?

You organized examples in the classic format. We will pick examples automatically. There is no need to override the `examples` section.

**Comment by pvint** [comment]
Perfect, thank you Ivan. (And also, thank you for saving me the time to figure that out myself!)

**Comment by ivankravets** [comment]
Thanks as well for your amazing contribution to the open-source!

**Pull request merged**
